### ISSUE TITLE
Release Schedule and Blockers

### ISSUE THREAD

**Issue by wbarnha** [uriyyo/fastapi-filters#294]
Hi Yurii, thanks for making this project! I would like to see a version of this released soon so I can tinker with using this alongside newer versions of FastAPI, since I see the last release has a version limit of `'fastapi<0.90.0,>=0.89.1'`. Is there anything I can do to help you get a release out sooner?

**Comment by uriyyo** [comment]
Hi @wbarnha,

Sorry for long response, I will try to release new version with unpinned fastapi version

**Comment by uriyyo** [comment]
Hi @wbarnha,

Looks like we don't have upper limit for fastapi version - https://github.com/uriyyo/fastapi-filters/blob/5c83d3156476333cf74251b368349969a0ad7714/pyproject.toml#L24

**Comment by wbarnha** [comment]
Just glanced over the commits, I'm not sure where my issue could have come from. Odd. 😕

**Comment by uriyyo** [comment]
Maybe you used an older version? There should be no issue with lastest one

**Comment by wbarnha** [comment]
I see what's going on now: https://github.com/tiangolo/sqlmodel/blob/main/pyproject.toml#L39 has a requirement for newer versions of pydantic and I'm trying to integrate this into an existing project using `sqlmodel`. ☹️

**Comment by uriyyo** [comment]
@wbarnha Can I close this issue?

**Comment by wbarnha** [comment]
Yes, sorry I didn't close it, I've been very distracted. I would like to at some point contribute to this project by having it support `sqlmodel` models in addition to `pydantic`, so I'll be back at some point!

**Comment by uriyyo** [comment]
@wbarnha See you!
